apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: cloudbeaver
        image: dbeaver/cloudbeaver
          - containerPort: 8978
