apiVersion: v1
kind: Secret
metadata:
    name: sb-jwt
    namespace: supabase
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:OCljhgTzJGvZtDqtEvacga0rtipFkWUiaj1NCBy818Q/BdwFSVk1lnzUXeLAoaSofz54CIx3bhJOe5HoMfx3hg==,iv:6hC2y8FLhpoMDeP6u3gIuPExSVdMXs5NA7OjulpsoU8=,tag:GMumPTGOvjAsNWFc3wXUTA==,type:str]
    anonKey: ENC[AES256_GCM,data:lBcA+dOasB76HBa00C3pNMLqhGT7XbCPu6/jscbVsro8Ry02l+VPBw+tMaIWSDpaTJk0mFxXziseuTXqbicGJsZrsyDK/VNkMxJmN+h1KFyBFR+3HI86mJGbmfXvTpiKHir+wh3BWep9nkiOn6234paty3pTxy4a3JgZFc/bMf7qhY2tc2wWpo2rUUE7zXrpPZq98jG3Y/81tWlsxRYtJHvnlAAHuJD0Eg==,iv:oxKyJ+xCqzlBdW9kh0dU9WWg9UICi+pcYEsTJBndNs4=,tag:Zmpj3b/FEzPQdl6MFokcZw==,type:str]
    serviceKey: ENC[AES256_GCM,data:5ZAoZfGIrJRjZrOBar9NE/WPIff/lFK4b4nCpbtCYYjUTBJ+V/IY/0YA5U3wFqeeF8Y6jNnS8d9SWtnglaF3sdMtsbyMtfEHVdQQxo1ySUMSdRes+4XK/BV705yPeln1MtUQOJW9jY+Wf4VNMeYg/bvUN9vZgIZSu+BeOpkwhqmHRDwbTqkaX1s+66tZTbp0PAD4llStuYYZM1nRoVV6FVH1VNxBmOwPpoboVcnSkUHV1MTd,iv:jb9bB6na5NIgGoZkyWG7CTqNWv2sIvJlGR4yRg6YL5k=,tag:l9350SqQjmsYZj6FvJ4ldw==,type:str]
sops:
    age:
        - recipient: age134ru89e5tulkzwlltv7mfx8l54m22mehuancqxpr4csz3hcukf4s8mg4cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Zk4rOGVVckJJbHJkdmdD
            d3hVdVZhS3AyZVk5bnNnbTZFa1JCTmoySjFRCmkxTWlhUW1kYm1nYXNROFpVaFg5
            MjUvKzFnUlJkQ1c3N2c5SjNVUDljNmsKLS0tIGx5MWZWNUZpTlMwTVBtQnh3UGo1
            YlNrYy9mTVdnMDMwY3FlUWk2Y0RPZlkKgDzSfYFRAfSHZFSwkc86cxER8Rmvd/pg
            +Go9LVRnHYciSO6JfoI4ZQpiAwhkAJOAatgjYDgOPFEXNiEp1z8RVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T20:33:32Z"
    mac: ENC[AES256_GCM,data:26CNeIOY/Jt4KI8lOZADc1iUNpJhXHlYBb/rOiPSC/tFnKUSWB3pWp9DOR72YTrRhLImrFpeO8KpmWORYc+9P0hVXbBH1fs0Nm6qjz8gHzFUAU7BRfaCpR88Yzsev9vlbaq8l+w1shhnaYY8V3X0il2QzFBPDdLxaUbWEQs2wyw=,iv:KIeWCCP5ZsVULtweI6nKZemXiFwhzWXH/AYQFPHAKNk=,tag:u6NdRlsw3dF/YsR2arDlnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sb-db
    namespace: supabase
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:twcHVKFUE3qMZpwcliX8Hmkh3TXLKjkGyrbn14adIC20nhkAxs2L+JFjIDCKRN3/,iv:NZa6eJAVToyvaQX8WU+z3xlEACM0b7pmwIxZMp8KoEg=,tag:v8rTfj2M87Wpee+GQJGmDw==,type:str]
    password_encoded: ENC[AES256_GCM,data:RDxxbAecqhjsFWNbgh3QiNTRxeEvq9PvhybR6IDJCIcxw2SakwusJFUdqYuAWqQT,iv:NYcQc5J2zbb0iQH98NmCEsaZ+yJbKmR2DP9FiuCNcx4=,tag:msNTmt/m8XT3fRX62G4QUw==,type:str]
    database: ENC[AES256_GCM,data:WED3FzZu7/o=,iv:F5ovi8sOL5gaZdUmajvNkXQ/GdtnvNnGQd+iYzy6eU4=,tag:bkgDw12LcNTMWBwuX251rA==,type:str]
sops:
    age:
        - recipient: age134ru89e5tulkzwlltv7mfx8l54m22mehuancqxpr4csz3hcukf4s8mg4cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Zk4rOGVVckJJbHJkdmdD
            d3hVdVZhS3AyZVk5bnNnbTZFa1JCTmoySjFRCmkxTWlhUW1kYm1nYXNROFpVaFg5
            MjUvKzFnUlJkQ1c3N2c5SjNVUDljNmsKLS0tIGx5MWZWNUZpTlMwTVBtQnh3UGo1
            YlNrYy9mTVdnMDMwY3FlUWk2Y0RPZlkKgDzSfYFRAfSHZFSwkc86cxER8Rmvd/pg
            +Go9LVRnHYciSO6JfoI4ZQpiAwhkAJOAatgjYDgOPFEXNiEp1z8RVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T20:33:32Z"
    mac: ENC[AES256_GCM,data:26CNeIOY/Jt4KI8lOZADc1iUNpJhXHlYBb/rOiPSC/tFnKUSWB3pWp9DOR72YTrRhLImrFpeO8KpmWORYc+9P0hVXbBH1fs0Nm6qjz8gHzFUAU7BRfaCpR88Yzsev9vlbaq8l+w1shhnaYY8V3X0il2QzFBPDdLxaUbWEQs2wyw=,iv:KIeWCCP5ZsVULtweI6nKZemXiFwhzWXH/AYQFPHAKNk=,tag:u6NdRlsw3dF/YsR2arDlnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sb-dashboard
    namespace: supabase
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:eeeydw==,iv:cekNa72paLYxPDWeo5p94SlpxpTMpPb4BLPGWB6fp1o=,tag:WJ6YXrxMgltS9EBMGlXnaA==,type:str]
    password: ENC[AES256_GCM,data:PN5VSrEzDP/7iNV3FHL0jy1G1umkF01Eil+iLOq6nBI=,iv:U70XUjwcmVdLXvLvf7d+TBnq6xEMg+5X7w32PZf6szo=,tag:N6BROBbSka7zvnL5How1cQ==,type:str]
    openAiApiKey: ""
sops:
    age:
        - recipient: age134ru89e5tulkzwlltv7mfx8l54m22mehuancqxpr4csz3hcukf4s8mg4cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Zk4rOGVVckJJbHJkdmdD
            d3hVdVZhS3AyZVk5bnNnbTZFa1JCTmoySjFRCmkxTWlhUW1kYm1nYXNROFpVaFg5
            MjUvKzFnUlJkQ1c3N2c5SjNVUDljNmsKLS0tIGx5MWZWNUZpTlMwTVBtQnh3UGo1
            YlNrYy9mTVdnMDMwY3FlUWk2Y0RPZlkKgDzSfYFRAfSHZFSwkc86cxER8Rmvd/pg
            +Go9LVRnHYciSO6JfoI4ZQpiAwhkAJOAatgjYDgOPFEXNiEp1z8RVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T20:33:32Z"
    mac: ENC[AES256_GCM,data:26CNeIOY/Jt4KI8lOZADc1iUNpJhXHlYBb/rOiPSC/tFnKUSWB3pWp9DOR72YTrRhLImrFpeO8KpmWORYc+9P0hVXbBH1fs0Nm6qjz8gHzFUAU7BRfaCpR88Yzsev9vlbaq8l+w1shhnaYY8V3X0il2QzFBPDdLxaUbWEQs2wyw=,iv:KIeWCCP5ZsVULtweI6nKZemXiFwhzWXH/AYQFPHAKNk=,tag:u6NdRlsw3dF/YsR2arDlnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sb-realtime
    namespace: supabase
type: Opaque
stringData:
    secretKeyBase: ENC[AES256_GCM,data:nRn2/YYB1iMPDAqDXk+vYJV6dFQI83+yQDh+TSK0rgmWM2bVsrQHfPMd9k9AU0b2IdBxG9eZ0zgpvPSgayC0sfG3Et8m7f1v3mCtITU0XKnv2J/9dOcRJQ==,iv:TGSJSbifnXXFijYuH5LJHolNbJF/Pg3Z5oZx70kbBGE=,tag:O8HDuRvW/EfxrrsaWQG0WA==,type:str]
    dbEncKey: ENC[AES256_GCM,data:qyRC5CxhQkhNBetrqHUI/Q==,iv:IKlHLWgG4pdBE/qip4kZIiCDzMsFV+HOVnpBePtJCqw=,tag:UeBHKmwznUIlgKOS7LH3yA==,type:str]
sops:
    age:
        - recipient: age134ru89e5tulkzwlltv7mfx8l54m22mehuancqxpr4csz3hcukf4s8mg4cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Zk4rOGVVckJJbHJkdmdD
            d3hVdVZhS3AyZVk5bnNnbTZFa1JCTmoySjFRCmkxTWlhUW1kYm1nYXNROFpVaFg5
            MjUvKzFnUlJkQ1c3N2c5SjNVUDljNmsKLS0tIGx5MWZWNUZpTlMwTVBtQnh3UGo1
            YlNrYy9mTVdnMDMwY3FlUWk2Y0RPZlkKgDzSfYFRAfSHZFSwkc86cxER8Rmvd/pg
            +Go9LVRnHYciSO6JfoI4ZQpiAwhkAJOAatgjYDgOPFEXNiEp1z8RVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T20:33:32Z"
    mac: ENC[AES256_GCM,data:26CNeIOY/Jt4KI8lOZADc1iUNpJhXHlYBb/rOiPSC/tFnKUSWB3pWp9DOR72YTrRhLImrFpeO8KpmWORYc+9P0hVXbBH1fs0Nm6qjz8gHzFUAU7BRfaCpR88Yzsev9vlbaq8l+w1shhnaYY8V3X0il2QzFBPDdLxaUbWEQs2wyw=,iv:KIeWCCP5ZsVULtweI6nKZemXiFwhzWXH/AYQFPHAKNk=,tag:u6NdRlsw3dF/YsR2arDlnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sb-meta
    namespace: supabase
type: Opaque
stringData:
    cryptoKey: ENC[AES256_GCM,data:c2O8HrEF5es5odvLIa4wzfEKBrsh2gXCY77QrEQxLizqsjb76rRohq5/VgU43wDsOiM2elGUQ8zX3EGsuB8/qQ==,iv:6zo9xPo+ekguXglBMNylittxHVgwgcFgI+j4epOoZU8=,tag:AvLrfB0CzMBlCDxkdk4CPQ==,type:str]
sops:
    age:
        - recipient: age134ru89e5tulkzwlltv7mfx8l54m22mehuancqxpr4csz3hcukf4s8mg4cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Zk4rOGVVckJJbHJkdmdD
            d3hVdVZhS3AyZVk5bnNnbTZFa1JCTmoySjFRCmkxTWlhUW1kYm1nYXNROFpVaFg5
            MjUvKzFnUlJkQ1c3N2c5SjNVUDljNmsKLS0tIGx5MWZWNUZpTlMwTVBtQnh3UGo1
            YlNrYy9mTVdnMDMwY3FlUWk2Y0RPZlkKgDzSfYFRAfSHZFSwkc86cxER8Rmvd/pg
            +Go9LVRnHYciSO6JfoI4ZQpiAwhkAJOAatgjYDgOPFEXNiEp1z8RVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T20:33:32Z"
    mac: ENC[AES256_GCM,data:26CNeIOY/Jt4KI8lOZADc1iUNpJhXHlYBb/rOiPSC/tFnKUSWB3pWp9DOR72YTrRhLImrFpeO8KpmWORYc+9P0hVXbBH1fs0Nm6qjz8gHzFUAU7BRfaCpR88Yzsev9vlbaq8l+w1shhnaYY8V3X0il2QzFBPDdLxaUbWEQs2wyw=,iv:KIeWCCP5ZsVULtweI6nKZemXiFwhzWXH/AYQFPHAKNk=,tag:u6NdRlsw3dF/YsR2arDlnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sb-s3
    namespace: supabase
type: Opaque
stringData:
    keyId: ENC[AES256_GCM,data:SCQsxFRnSm0Pxaro+uizSV3tEFr+/u45Z0Cz/aqG4Bk=,iv:TDiY38KAMksZPKdk/9KHp9G6RGuPecweLC3jrn+zF6k=,tag:Y5cjog+0eyXVliH4gPlCzg==,type:str]
    accessKey: ENC[AES256_GCM,data:CHsAAW34Fs4qlqaoK/5seWKJ2JWF3rzQ69eY157fSnpOBdiTCNdJ4HKXrAU6qt4z1XqVix8NZeV+ykOaJ1FzPw==,iv:h7kVtdPXsJKgwVskV1jJe91DiPaYIE06SKMYzdYQ4t4=,tag:x7cQ6tYIL8z4I//5/7+6ow==,type:str]
sops:
    age:
        - recipient: age134ru89e5tulkzwlltv7mfx8l54m22mehuancqxpr4csz3hcukf4s8mg4cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Zk4rOGVVckJJbHJkdmdD
            d3hVdVZhS3AyZVk5bnNnbTZFa1JCTmoySjFRCmkxTWlhUW1kYm1nYXNROFpVaFg5
            MjUvKzFnUlJkQ1c3N2c5SjNVUDljNmsKLS0tIGx5MWZWNUZpTlMwTVBtQnh3UGo1
            YlNrYy9mTVdnMDMwY3FlUWk2Y0RPZlkKgDzSfYFRAfSHZFSwkc86cxER8Rmvd/pg
            +Go9LVRnHYciSO6JfoI4ZQpiAwhkAJOAatgjYDgOPFEXNiEp1z8RVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T20:33:32Z"
    mac: ENC[AES256_GCM,data:26CNeIOY/Jt4KI8lOZADc1iUNpJhXHlYBb/rOiPSC/tFnKUSWB3pWp9DOR72YTrRhLImrFpeO8KpmWORYc+9P0hVXbBH1fs0Nm6qjz8gHzFUAU7BRfaCpR88Yzsev9vlbaq8l+w1shhnaYY8V3X0il2QzFBPDdLxaUbWEQs2wyw=,iv:KIeWCCP5ZsVULtweI6nKZemXiFwhzWXH/AYQFPHAKNk=,tag:u6NdRlsw3dF/YsR2arDlnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: seanpe-api-db-password
    namespace: supabase
type: Opaque
stringData:
    SEANPE_API_DB_PASSWORD: ENC[AES256_GCM,data:urkOMIkb7/KxfK+DfJgklDbSxmIVuaAvqpgVFKaIwpQqrpty1Aj8MJGoRHeDSRzA,iv:I+hK9xSiKYgKafLeggvrpHg7bqanfGoDpy1l0HZ8Y4U=,tag:Z7Dop/8buRmxXaNaHEeb0w==,type:str]
sops:
    age:
        - recipient: age134ru89e5tulkzwlltv7mfx8l54m22mehuancqxpr4csz3hcukf4s8mg4cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Zk4rOGVVckJJbHJkdmdD
            d3hVdVZhS3AyZVk5bnNnbTZFa1JCTmoySjFRCmkxTWlhUW1kYm1nYXNROFpVaFg5
            MjUvKzFnUlJkQ1c3N2c5SjNVUDljNmsKLS0tIGx5MWZWNUZpTlMwTVBtQnh3UGo1
            YlNrYy9mTVdnMDMwY3FlUWk2Y0RPZlkKgDzSfYFRAfSHZFSwkc86cxER8Rmvd/pg
            +Go9LVRnHYciSO6JfoI4ZQpiAwhkAJOAatgjYDgOPFEXNiEp1z8RVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T20:33:32Z"
    mac: ENC[AES256_GCM,data:26CNeIOY/Jt4KI8lOZADc1iUNpJhXHlYBb/rOiPSC/tFnKUSWB3pWp9DOR72YTrRhLImrFpeO8KpmWORYc+9P0hVXbBH1fs0Nm6qjz8gHzFUAU7BRfaCpR88Yzsev9vlbaq8l+w1shhnaYY8V3X0il2QzFBPDdLxaUbWEQs2wyw=,iv:KIeWCCP5ZsVULtweI6nKZemXiFwhzWXH/AYQFPHAKNk=,tag:u6NdRlsw3dF/YsR2arDlnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
