apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
  namespace: networking
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - "tunnel"
        - "--config"
        - "/etc/cloudflared/config/credentials.json"
        - "run"
        - "seanpe-k8s-homelab"
        volumeMounts:
        - name: creds-volume
          mountPath: /etc/cloudflared/config
          readOnly: true
      volumes:
      - name: creds-volume
        secret:
          secretName: tunnel-credentials 
