apiVersion: v1
kind: Secret
metadata:
    name: seanpe-api
    namespace: apps
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:yxIJw3C2+bbQ+MezlxX5agwFybTVaecQzp4JNFnibljm91O044zKI2kK0/LUkPSwEksJ7//HJ0D4iFhJCmaHDzB05Mh/fTuY8m1h6qCZgxj+MkrsJJN8ZghmaeU11gMJIjXF45A8pGChV0NdBNeOjglwxKD91yAqHfv6neAqcM6KY9u2yfW5AIMfSJiUH9c0K1I1yw==,iv:mbY+NPj6F9NfTNblJoDJcJaOWIXaRmU//6HcGGDS4wU=,tag:4P4WUm+44EnwmiZLFOdaEg==,type:str]
    API_KEY: ENC[AES256_GCM,data:Y7hciEnVlkcNpVE0MFbKEXjDYvq031Nx5Y32xhft6c/PImb6+56ebrBoLg==,iv:3Sb3ohwQEkPcN0I4bkkFXr9RBb3tv64G5/ng46cpBkc=,tag:f3r5bkotsH56NteTiVzP8w==,type:str]
sops:
    age:
        - recipient: age134ru89e5tulkzwlltv7mfx8l54m22mehuancqxpr4csz3hcukf4s8mg4cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eHJqamNpZTM5ZUtVMFlE
            emF2MXFaY2V2OGg3L0duT3FTcGhtUCtnOEI0ClZ1VzAxaUFRSHYwOXpGdWdtN3lz
            c3VhMlcvMDdhREo4ZjRUOWpINEEyYk0KLS0tIFlOWTRla0FOM05zMWRKYmFtWWhD
            clQrbjc1M1NWYTVVU3ZGWHhFOGNIZ2cKKdJfOLXceoQcT95UL95L+TrYwT1JmfJy
            oogQgK02AwDAmYrhS586gFw12UZSfqE8BubP2GneOyh0dNspJ+GrCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T20:33:33Z"
    mac: ENC[AES256_GCM,data:ziGbpvkFH1w+7TQ9SZ4pMYzY9OFVrMLzU/4gMD0FX8YwRmkw8oAe0r8z5tVcaXm+DaVbeORtmKsL5AtASYWbntnimtymUp+j041ri8D5ceGbLAQngnEJfxEF8KBLz2bLxS6aYBVSEAyiT8bltjTrXBy6ukiQjdZ7K1jX3KVpXts=,iv:5Di6rzfoKmHceKtFpJXaZZuF2GnToEsgJ4RBWdbF4CA=,tag:IL7h8Xjk0ZNHy2D30Wdp9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
