apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: networking
data:
  proxy.conf: |
    server {
      listen 80;
      
      server_name ~^(?<subdomain>.+)\.seanpe\.io$;

      location / {
            # This assumes a naming convention where the subdomain matches the service name.
            # It also assumes the target services are in the 'apps' namespace.
            proxy_pass http://$subdomain-service.apps:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
