apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-internal-proxy
  namespace: networking
  labels:
    app: nginx-internal-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-internal-proxy
  template:
    metadata:
      labels:
        app: nginx-internal-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        # This mount instruction tells the container where to put the config file.
        - name: nginx-config-volume
          # This is the path inside the NGINX container for custom configs.
          mountPath: /etc/nginx/conf.d/default.conf
          # 'subPath' tells it which key from the ConfigMap to use as the file.
          subPath: proxy.conf
      volumes:
      # This volume definition links our 'nginx-config-volume' to the ConfigMap
      - name: nginx-config-volume
        configMap:
          name: nginx-proxy-config # Must match the ConfigMap name from Step 1

---
# The '---' separates multiple YAML documents in a single file

apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-proxy-svc
  namespace: networking
spec:
  selector:
    # This selector must match the 'app' label in the Deployment above.
    app: nginx-internal-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
