apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: networking
data:
  config.yaml: |
    ingress:
      - hostname: portfolio.seanpe.io
        service: http://seanpe-com-service.apps:80
      - service: http_status:404
