## Tunnel secret cmd:
## cloudflared tunnel token <tunnel-name>
## kubectl create secret generic tunnel-token-secret --from-literal=token=<TUNNEL_TOKEN>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
  namespace: networking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - "tunnel"
        - "--config"
        - "/etc/cloudflared/config.yaml"
        - "run"
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              # This securely injects the token from the command listed above
              name: tunnel-token-secret
              key: token
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cloudflared
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: cloudflared-config
