apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared-configmap.yaml
  - cloudflared-deployment.yaml
  - tunnel-credentials.sops.yaml   # credentials file: keeps the tunnel locally managed
