apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-main
  namespace: databases
spec:
  instances: 1
  bootstrap:
    initdb:
      secret:
        name: postgres-secret # Points to our encrypted secret
  storage:
    size: "10Gi"
    storageClass: "local-path"
