apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      # --- THE FIX #1: Use a chart version that packages Postgres 17 ---
      version: "16.7.27"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  values:
    # --- THE FIX #2: Explicitly use a known-good, free image for PG 17 ---
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "17.6.0-debian-12-r0" # A known-good tag for this app version

    # --- The rest of your configuration stays the same ---
    auth:
      existingSecret: "postgres-secret"
      secretKeys:
        postgresPasswordKey: "postgres-password"
      database: "homelab"
    primary:
      persistence:
        enabled: true
        storageClass: "local-path"
        size: 10Gi
