apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "14.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: "postgres-secret"
      secretKeys:
        postgresPasswordKey: "postgres-password"
      database: "homelab"
    primary:
      persistence:
        enabled: true
        storageClass: "local-path"
        size: 10Gi
