auth:
  existingSecret: "postgres-secret"
  secretKeys:
    postgresPasswordKey: "postgres-password"
  database: "homelab"
primary:
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 10Gi
