apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "14.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami 
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: postgresql-helm-values


replacements:
  - source:
      kind: ConfigMap
      name: postgresql-helm-values
      version: v1
    target:
      kind: HelmRelease
      name: postgresql
      fieldPaths:
      - spec.valuesFrom.0.name
