apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml # The encrypted secret file
  - helmrelease.yaml

configMapGenerator:
- name: postgresql-helm-values
  namespace: databases
  files:
  - values.yaml=helm-values.yaml 
