apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml # The encrypted secret file
  - helmrelease.yaml

configMapGenerator:
- name: postgresql-helm-values
  namespace: databases
  files:
  - values.yaml=helm-values.yaml 

replacements:
  - source:
      kind: ConfigMap
      name: postgresql-helm-values
      version: v1
    target:
      kind: HelmRelease
      name: postgresql
      fieldPaths:
      - spec.valuesFrom.0.name
