auth:
  # Tell Postgres to use the secret we just created
  existingSecret: "gitea-db-secret"
  secretKeys:
    # Map the key from our secret to the key Postgres expects
    adminPasswordKey: "POSTGRES_PASSWORD"
  # Pre-create the database Gitea will use
  database: "gitea"
primary:
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 15Gi
