apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    # The namespace will be applied by our Kustomize overlay later
    namespace: databases
type: Opaque
stringData:
    #ENC[AES256_GCM,data:p73ObO1GLTHQgdY8rRywo1hh9NmJGerjRPoK9nnFGjkQbx08RhLWEAptEIOeTwr1X28sIm1ND5M5dhWTkahW0Ns=,iv:9Ca8qsCeTRXZysaj+BkHTan3JAqlV96Z07WI1Bpabv8=,tag:72ppr3xQ9/H21GDGFJ1eHg==,type:comment]
    #ENC[AES256_GCM,data:h8tae2eMUMvorezL50aUP3YuUmmM3yvtT4qAvfsi71+y5v372atCOSDEn7yBCTc81pgNim75bmaVjmTV+K5U/Zt0cvo=,iv:hcfoQb480KT7ppW0TsFqk2c4qSl2WC4+9CnkZqG1I1o=,tag:GkGB0LJIjuZqARldyzeuFQ==,type:comment]
    #ENC[AES256_GCM,data:algVvO4uUQsqicOie1//2BSElJ3GRmhmfehgaOr8GQctwylFGpBsi55ai1CJ6wXw/B9fp4J9,iv:goRyc+FSrmkQHU84NEYKd/nAEhfCIKZmjM/kUVXjkmM=,tag:UKTUz6M+ehgO5JOBSkt7lA==,type:comment]
    #ENC[AES256_GCM,data:n4cwEoEUdVYeTWBR7uCHjA==,iv:Ct6DNQnqHN4daGEsgDHIYV8JKJZeI35g3szLXRsHQPo=,tag:ZV37N742GYMOAd9462pkcA==,type:comment]
    postgres-password: ENC[AES256_GCM,data:2BCG088wStQakCnkpRKdTg==,iv:TNrVkykw8FSUQprmKOOlRyMSBIuQlWM+WC8I/spT+rE=,tag:wGeejLNHZE1dhwO35Ckdxw==,type:str]
sops:
    age:
        - recipient: age134ru89e5tulkzwlltv7mfx8l54m22mehuancqxpr4csz3hcukf4s8mg4cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSVRoSml5M2UzVEhLZlRn
            cThCaFdlc2lsbUJ0TWFaRy9lZmF5Z0pjbFJRCmd4aGhhYlNwTFZFby9nZEZxdzM4
            bE1FNVlnNExHZElvTGNYZ25uUTV5VkEKLS0tIFExYzU0SFR0MjE2VG9jV3lJcUFR
            SGJwb3NxbndvaE9qYXNVdklkVGtsRUkKI92jfBmFbCOy9bnzp5Biu8qOjfj4ico2
            j1hJUER0L7WT9oWejeKu2u3qX8lErWPLk9C9QVjjFwyrl40s6+dRkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T16:32:21Z"
    mac: ENC[AES256_GCM,data:qfJVvOy0Su4qVg/BRq0kqnM4xllmRDTLwh4A+c+0JKvLCDhHKF33WW7GxtCJjFzgnUXZIsP8lxPu81hDOPrRhtZ0Bo1FG1lD8jYzrxXyqXoV6uVueT3t0yz4oZa1C6rFdecjIOvr80eVNNBkwlin92hg8D7Vg5jAr88aB6e5CwI=,iv:NHwxlvYr/TWAwMBuukpWQ3cpKOhh2/tPlAwLaJnHi9A=,tag:avrbw1jeZ2nz6XKSjzssEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
