apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system # HelmRepository sources must be in the flux-system namespace
spec:
  interval: 30m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
