apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg-system # The operator runs in its own dedicated namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.26.1" # Pin to a recent stable version
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
