## THIS IS A TEMPLATE FILE
## YOU MUST REPLACE THE TOKEN WITH YOUR OWN
## recommended: create a another file with the name cloudflared-secret.yaml and fill it with your token
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: networking
stringData:
  # The key is 'token', and the value is your long tunnel token. You can find it from the config file
  token: "<TUNNEL_TOKEN>"
